biocore/unifrac

.travis.yml, setup.py
Add test in .travis.yml, should be good to merge if tests pass.
=> BLD/TST: Fix pip install -e .

q2_state_unifrac/plugin_setup.py
This property was dropped sometime recently, this patch removes that
property.
Related post:
https://github.com/qiime2/q2-feature-table/issues/108#issuecomment-316460800
=> BUG: Properties('uniform-sampling') is deprecated

sucpp/affinity.hpp, sucpp/unifrac.cpp
OSX and Linux affinity. Still testing.
=> CPU affinity

q2_state_unifrac/tests/test_api.py
Not all tests were ported, but the appropriate issues have been opened, see: #34, #35 and #36.
=> Port edge cases from skbio

setup.py, sucpp/Makefile
Let's see how travis likes this.
=> If this works, then we may be able to proceed to a conda-build

sucpp/Makefile, sucpp/unifrac.cpp, sucpp/unifrac.hpp
Adding link instructions for pthreads
=>  Fix compilation with Intel Compiler 

unifrac/_api.pyx, unifrac/tests/test_api.py
Addresses #71 
**Old Behavior**
```
>>> from unifrac import stacked_faith
>>> faith_pd_series = stacked_faith('foo.biom', 'bar.nwk')
>>> faith_pd_series.name
None
```
**New Behavior**
```
>>> from unifrac import stacked_faith
>>> faith_pd_series = stacked_faith('foo.biom', 'bar.nwk')
>>> faith_pd_series.name
'faith_pd'
```
=> Name stacked faith series

README.md, sucpp/su.cpp
Just realized the citation wasn't there.
=> Adding Striped UniFrac citation

.travis.yml, sucpp/Makefile, unifrac/_methods.py, unifrac/tests/test_methods.py
Fixes #31 
Added lines to set up environment specific to os being tested. After talking with @ElDeveloper, also updated requirements to latest qiime environment.
=> added osx build and update requirements

README.md
=> Readme faith pd

unifrac/__init__.py, unifrac/_api.pyx, unifrac/tests/test_api.py
=> change name stacked_faith to faith_pd

README.md
forgot to change this line with #83
=> changed stacked_faith to faith_pd in README

.travis.yml, sucpp/test_su.cpp
=> Fix segmentation fault in testing

setup.py
=> Update version string and `setup.py`

README.md
=> add conda install to readme

README.md
Fixes #97 as well as updates some other QIIME information reflected in the updated version of QIIME (2019.7)
=> update qiime information in README

sucpp/Makefile, sucpp/api.cpp, sucpp/su.cpp, sucpp/unifrac.cpp, sucpp/unifrac.hpp, sucpp/unifrac_task.cpp, sucpp/unifrac_task.hpp
Several optimizations for GPU, using OpenACC.
A proper Makefile for compiling with PGI is also included.
The new code seems to be significantly faster both on CPUs and GPUs.
=> Improved GPU port

README.md, docs/compile_gpu.README.md
=> Add GPU compile instructions

.github/workflows/main.yml
Avoid mixing packages from base and conda-forge repos.
=> Fix build issues

sucpp/faithpd.cpp, sucpp/su.cpp
Fix compute_status_messages in both ssu and faithpd.
They had both a typo and were the wrong size.
=> Fix compute_status_messages

.github/workflows/main.yml, README.md, setup.py, unifrac/__init__.py, unifrac/_api.pxd, unifrac/_api.pyx, unifrac/_methods.py, unifrac/tests/test_api.py, unifrac/tests/test_methods.py
Depends on biocore/unifrac-binaries#2
Note this PR is incomplete but represents a passing API call with in memory objects
=> WIP: support for passing biom and the tree in memory

.github/workflows/main.yml, unifrac/_api.pyx
Test out against more versions of Python
=> Expand build matrix

unifrac/_methods.py, unifrac/tests/test_methods.py
=> Remove extraneous str casts

.github/workflows/main.yml, unifrac/__init__.py, unifrac/_api.pxd, unifrac/_api.pyx, unifrac/_methods.py, unifrac/tests/test_api.py, unifrac/tests/test_methods.py
@sfiligoi could you review when you have a moment?
=> Some maintenance items
