biocore/unifrac

sucpp/Makefile
sucpp/api.cpp
sucpp/api.hpp
sucpp/su.cpp
sucpp/task_parameters.hpp
sucpp/test_su.cpp
sucpp/unifrac.cpp
unifrac/_api.pxd
unifrac/_api.pyx
unifrac/_methods.py
unifrac/tests/test_api.py

Should be quick, although I'd understand if an integration test is requested. By disregarding tips, approximately 50% of the tree does not get evaluated for UniFrac, which in turn removes about 50% of the compute. This works though because we're, in effect, collapsing the phylogeny slightly which is similar to using a coarser OTU picking level (e.g., 99% vs 97%).
Thanks, @dkoslicki, for the idea! This was the easiest thing to do first -- collapsing at a deeper level required a bit more changes.

Short circuit

---

sucpp/api.cpp
sucpp/api.hpp
sucpp/su.cpp
sucpp/test_su.cpp
sucpp/tree.cpp
sucpp/tree.hpp
sucpp/unifrac.cpp
sucpp/unifrac.hpp
unifrac/_api.pxd

@ElDeveloper This is the PR. It spans three items:
- explicitly test to make sure the observation IDs in the table are a subset of the tip names in the tree
- provide human readable messages when an error occurs (e.g., missing a filename)
- fixes a bug where quoted structural characters were not appropriately being captured

Table tree overlap

---

.travis.yml
setup.py
sucpp/Makefile
sucpp/test_api.cpp

- changed `install` and `develop` commands for calling `make` into a more general `build_ext` which runs any time the `Extension` is built
- fixed a bug that caused an abort trap on some systems/environments
- removed dependencies on qiime build and specified packages

changes for conda build

---

README.md

The lack of tabs cause the README to not be rendered properly.
Fixes #82

reformat readme so citation is in pre-formatted version

---

sucpp/su.cpp
sucpp/unifrac.cpp

Should resolve #63 . Before these changes if I ran something like `for run in {1..100}; do ssu -i table.biom -t tree.nwk -m unweighted -o foo -n 8 & done` (thanks @thermokarst ) I would get around 0-5 exiting with a segfault. With these changes, I can do 1000 runs several times and get no seg faults, so I think we've pinned it down for now.
As an added bonus, I have wrapped the `ssu` CLI in a signal handler so users don't accidentally kill the process when trying to check the status before the program enters `process_stripes`
```
$ ssu -i table.biom -t tree.nwk -m unweighted -o foo -n 2                                                                                  
^Z …
```

Fix stochastic segfault #63

---

.travis.yml

Closes #101 
It addresses a failed Rcpp installation by changing the CRAN repo.
As a bonus, I have added a variable `build: 0` to the bonus. In the future, if builds need to be restarted for some reason, without changing other code, you can increment or decrement this variable.

Fix R build

---

sucpp/su.cpp
sucpp/test_su.cpp
sucpp/unifrac.cpp
sucpp/unifrac.hpp
sucpp/unifrac_task.cpp
sucpp/unifrac_task.hpp

Add OpenACC support in unifrac.
Adds a memory buffer copy, which can add up to a 10% performance hit in non-acc code.

Add OpenACC support

---

unifrac/_methods.py
unifrac/tests/test_methods.py

This PR adds `_validate()` calls to the other unifracs, and creates a `_validate_meta()` function to check tree and table inputs to _meta_unifrac() and raise appropriate error messages. Closes #105.
Though I did some hacky playtesting in iPython, *this code has not been tested properly*. Sorry! My time's pretty tight right now, and I won't be able to build and test properly in the next few days.  Here's hoping Travis smiles upon me. :crossed_fingers:

Adds validation to other Unifracs

---

sucpp/api.cpp

This `fprintf` was producing really interesting numbers because it wasn't being told what value to plug into `%d`.
NOTE: this PR has not been tested locally. Sorry!

BUG: format string missing value producing arbitrary values

---

sucpp/unifrac_task.cpp

Luckily, there is a check in the loop that makes this only a minor performance issue.

Bug in calculating the sample_steps, was orders of magnitude too big.

---

sucpp/api.cpp

I found two more places in the code with the same issue I attempted to correct in #107. These were not discovered in actual use - I'm just assuming that failure to pass a value to `fprintf` will produce unwanted results for someone someday.
I've attempted to use existing variables in all three locations this time (rather than re-calculating the number of stripes), but I haven't used C++ before, and _have not tested_. One of these days, I promise I'll figure out how to build/test this thing, but in the meantime, tread with caution. :)

BUG: format string missing value

---

sucpp/api.cpp
sucpp/api.hpp
sucpp/su.cpp
sucpp/test_api.cpp
sucpp/test_su.cpp
sucpp/unifrac.cpp
sucpp/unifrac.hpp

The original merge used a lot of memory and had a sub-optimal memory access pattern.
The refactoring minimizes the use of memory, improves memory access pattern and add support for using a disk buffer for holding the intermediate matrix.
All combined, it allows to either drastically reduce the runtime or the memory usage.

Improve merge performance

---

sucpp/biom.cpp
sucpp/biom.hpp
sucpp/test_su.cpp
sucpp/tree.cpp
sucpp/tree.hpp
sucpp/unifrac.cpp
sucpp/unifrac.hpp
sucpp/unifrac_task.cpp
sucpp/unifrac_task.hpp

Contains the following improvements:
* Chunk the compute of emb_buffers, to fit large problems in CPU cache
* Add explicit check for zero elements in Unweighted, to optimize for the sparse nature of the emb_buffer
* Move unweighted to 64-bit packed format, to maximize sparse checking efficiency
* Add zero checks and use distributed properties in UnnormalizedWeighted and NormalizedWeighted
It also contains some additional const guarantees, that allow for better algorithmic reasoning.

Improvements to cache locality and sparse vector handling

---

.github/workflows/main.yml
LICENSE
docs/compile_cpu.README.md
docs/compile_gpu.README.md
sucpp/Makefile
sucpp/affinity.hpp
sucpp/biom.cpp
sucpp/biom.hpp
sucpp/biom_interface.hpp
sucpp/su.cpp
sucpp/test_su.cpp
sucpp/tree.hpp
sucpp/unifrac.cpp
sucpp/unifrac.hpp
sucpp/unifrac_cmp.cpp
sucpp/unifrac_cmp.hpp
sucpp/unifrac_internal.cpp
sucpp/unifrac_internal.hpp
sucpp/unifrac_task.cpp
sucpp/unifrac_task.hpp

Slight change in the compile procedure to allow for CPU and GPU code paths to co-exist in a single installation.
The GPU compilation is now triggered by the presence of a ACC_CXX environment variable; the documentation has been updated accordingly.
When both CPU and GPU code paths are available, the code will use GPUs whenever possible.
The CPU path can be forced at runtime with UNIFRAC_USE_GPU=N.
Informative messages about CPU/GPU  switch can be enabled with UNIFRAC_GPU_INFO=Y.
Note: No change for MacOS, as GPU code paths are not supported there.

Change GPU compile to co-exist with CPU code path

---

README.md
docs/compile_cpu.README.md
docs/compile_gpu.README.md

Installing unifrac in the anaconda base seems to create conflicts; creating a new environment is safer.
Also update links to point to 0.20.2 (instead of 0.20.1).

Clarify installation and add reference to 0.20.2

---

sucpp/skbio_alt.cpp

Found and fixed a 32-bit truncation error in the PCOA compute code.

BUG FIX: PCOA compute was incorrect for large matrices

---

.github/workflows/main.yml
docs/compile_cpu.README.md
docs/compile_gpu.README.md

Update build instructions to use gcc 9.3 and HPC SDK 21.5.
Also cleaner build instructions for human builds.

Update build instructions with gcc 9.3 and HPC SDK 21.5

---

sucpp/api.cpp
sucpp/unifrac_cmp.cpp
sucpp/unifrac_task.cpp
sucpp/unifrac_task.hpp

Preciously, Unifrac could produce the wrong output when computing large matrices, due to 32-bit wraparound.
The limiting factor was: (n_samples x n_stripes) could not exceed 2^31 in GPU code, and 2^32 in CPU code.
Note: Was only a problem for large-memory GPUs, like the A100 and A40.

BUG FIX: Fix compute of large matrices

---

.github/workflows/main.yml
README.md
unifrac/_api.pxd
unifrac/_api.pyx
unifrac/_methods.py

Document that the treads parameter has been deprecated and that users should rely on env variables.
Also add the n_substeps to preserve the past behavior.

Deprecate threads and add n_substeps

---

.github/workflows/main.yml
unifrac/__init__.py
unifrac/_api.pxd
unifrac/_api.pyx
unifrac/_methods.py

Using condensed form requires several memory copies, which is both slower and uses more memory that using the matrix data layout.
The matrix varion of the API has been available in all the versions of unifrac-binaries.
We also disable the validation of the uffer in skbio, which requires at least 0.5.7.

Switch from condensed to matrix API calls

---

.github/workflows/main.yml
README.md
unifrac/__init__.py
unifrac/_api.pxd
unifrac/_api.pyx
unifrac/_methods.py

All unifrac to file functions now have an additional 
n_subsamples
parameter.
If >1, use the unifrac_multi_to_file_v2 API in the backend.
Also added the set_random_seed function.

Add support for multi unifrac to file

---

.github/workflows/main.yml
unifrac/_methods.py

Multi-unifrac HDF5 files can be huge.
The old eager semantics could make it impossible to load everything in memory.
The new semantics reads the data in memory only as-needed.
The major side effect is that the HDF5 is open (on read-only mode) for the lifetime of the returned object.

Switch h5unifrac_all to lazy load semantics 

---

setup.py
unifrac/tests/test_api.py

In scikit-bio change the name OTU in favor of taxon. See https://github.com/scikit-bio/scikit-bio/commit/c59a7755f7f0271bc3df783518e202bf4b9dcf1c
This commit update the test_api.py according to this new change in scikit-bio.
The original bug was reported [here](https://bugs.debian.org/1074302)

Update arguments name used in beta_diversity in tests
